# Generated by Django 5.2.10 on 2026-03-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
